# Generated by Django 4.0.5 on 2022-08-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo',
            field=models.CharField(max_length=200),
        ),
    ]
